import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/modules/NavBar/NavBar";
import Footer from "@/modules/Footer/Footer";
import { NavItem } from "@/interfaces/main";

const inter = Inter({ subsets: ["latin"] });

const navItems: NavItem[] = [
  {
    name: "Discover",
    link: "/discover",
  },
  {
    name: "creators",
    link: "/",
  },
  {
    name: "Sell",
    link: "/",
  },
  {
    name: "stats",
    link: "/",
  },
];
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar navItems={navItems} />

        {children}

        <Footer navItems={navItems} />
      </body>
    </html>
  );
}
